microsoft/kiota-dotnet

- src/Microsoft.Kiota.Abstractions.csproj
- src/QueryParametersBase.cs
I have stopped the release and caught this minor bug in my integration testing.
> - fixes a bug where empty query parameters would be passed

- CHANGELOG.md
- src/ApiClientBuilder.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
- src/extensions/IDictionaryExtensions.cs
- src/extensions/StringExtensions.cs
- src/serialization/ParseNodeFactoryRegistry.cs
- src/serialization/SerializationWriterFactoryRegistry.cs
- src/store/InMemoryBackingStore.cs
This is part of #12 
Changes include: -
- implement own version of TryAdd for dictionary
- change overload of string.split
- dropped use of range/index operators not available
> Changes target runtime to netstandard2.0

- .azure-pipelines/ci-build.yml
- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/ApiClientBuilderTests.cs
- Microsoft.Kiota.Abstractions.Tests/Microsoft.Kiota.Abstractions.Tests.csproj
- src/ApiClientBuilder.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
This PR closes https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/470
It fixes an issue with clients running versions before .NET 5 where modifying dictionary values while iterating was not allowed.
Tests have been added to reflect this change and a `net462` target added to the project to capture such issues in future tests.
**Background info**
- https://github.com/dotnet/runtime/pull/34667 and https://github.com/dotnet/runtime/issues/34606
> Fix for backing store registration in .net framework

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1346 and closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1443
Changes include : - 
- Resolves `DateTimeOffset` and `DateTime` objects to be placed in URL segments or query parameters to default to the ISO 8601
- Add explicit error message in the event that URI property is accessed without setting the "baseurl" path parameter (if needed)
- Adds tests to capture and validate these scenarios
> Default DateTime format in URL path/query to ISO 8601

- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/59
It simply adds a test to validate/prove that the `RequestInformation` abstraction fixes a the limitation that previously existed with `BaseRequest` that prevented it from having a proxy `baseUrl` due to the existence of special character like `?` or `&`.
> Validates proxy base url

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Mocks/TestEntity.cs
- Microsoft.Kiota.Abstractions.Tests/Store/InMemoryBackingStoreTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1448
It fixes a bug in the InMemoryBackingstore as it would fail to return changed properties if
- A property is a collection that was modified that was modified. This is resolved by annotation of the property with the size which is checked/synced when the property getter is called. 
- A property is a complex object(IBackedModel) that had one of its properties modified. This is now resolved by subscribing to the nested models events and using its changes to flag the property change.
> InMemoryBackingstore fixes

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/IRequestAdapter.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
- src/ResponseHandlerOption.cs
This PR is part of https://github.com/microsoft/kiota/issues/1858
Changes include : -
- Updates `Send*` methods in `IRequestAdapter` to move the `responseHanlderParameter`
- Adds the `SetResponseHandler` method to be able to directly add `IResposeHandler` to a request
- Adds the `GetRequestOption<T>` method to be able to get an `IRequestOption` instance by the type in O(1) time.
- Adds tests to validate
> Changes the responseHandler to be a requestOption

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
This PR bumps Tavis.UriTemplates to the latest version and creates a new release for the same.
> Bump Tavis.UriTemplates

- .azure-pipelines/ci-build.yml
- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
This PR creates a release candidate release for the library
Changes include -
- Ensure the nuget push task uses version greater than 5.2.0 to ensure debug symbols are pushed
- Include readme in nuget package in accordance with https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
- Fixed a couple of codesmells from sonarcloud in the `InMemoryBackingStore.cs`
> Release candidate 1 release

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
This PR closes #60
Changes include : - 
- Add checks to the  `AddQueryParameters` method to avoid adding empty collections and string to the `QueryParameters` when using request builders.
> Fixes empty query parameters

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Microsoft.Kiota.Abstractions.Tests.csproj
- Microsoft.Kiota.Abstractions.Tests/RequestHeadersTests.cs
- src/IRequestAdapter.cs
- src/IResponseHandler.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/NativeResponseHandler.cs
- src/NativeResponseWrapper.cs
- src/RequestHeaders.cs
- src/RequestInformation.cs
- src/ResponseHandlerOption.cs
- src/authentication/AllowedHostsValidator.cs
- src/authentication/AnonymousAuthenticationProvider.cs
- src/authentication/ApiKeyAuthenticationProvider.cs
- src/authentication/BaseBearerTokenAuthenticationProvider.cs
- src/authentication/IAccessTokenProvider.cs
- src/authentication/IAuthenticationProvider.cs
- src/extensions/IDictionaryExtensions.cs
- src/extensions/StringExtensions.cs
- src/serialization/IParseNode.cs
- src/serialization/ISerializationWriter.cs
- src/store/IBackingStore.cs
- src/store/InMemoryBackingStore.cs
This PR is part of https://github.com/microsoft/kiota/issues/2073
Changes include: -
- Adds nullable markers to APIs that can return null. 
- Adds nullable feature in project as well as net6.0 target to allow for proper feature functionality. Also sets `TreatWarningsAsErrors` to alleviate any potential mistakes being ignored.
> Adds support for nullable ref types

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/ApiClientBuilderTests.cs
- Microsoft.Kiota.Abstractions.Tests/Serialization/ParseNodeFactoryRegistryTests.cs
- Microsoft.Kiota.Abstractions.Tests/Serialization/SerializationWriterFactoryRegistryTests.cs
- src/ApiClientBuilder.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/serialization/ParseNodeFactoryRegistry.cs
- src/serialization/SerializationWriterFactoryRegistry.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1629
It changes the `ParseNodeFactoryRegistry` and `SerializationWriterFactoryRegistry` to hold the factories to alleviate race conditions reported when the collection is modified during the enabling of the backing store.
> Use ConcurrentDictionary for the registries. 

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670 and https://github.com/microsoft/kiota-serialization-json-dotnet/issues/69
Conflicting libraries for users on .NET 6 run into issues when forced to use the v7 of the library.
> Use sliding version for System.Diagnostics.DiagnosticSource

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Store/InMemoryBackingStoreTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
In the event that a property in an `IBackedModel` is also an `IBackedModel` or a collection of `IBackedModel`, a change in one of the properties is currently propagated up. However, the nested model only returns its changed properties which would create the issue where the payload generated creates the notion that the nested property has properties removed.
This PR, ensure the whole property is marked as "dirty" to prevent unwanted side effects when performing PATCH calls in nested property.
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1904
Querying the list of attendees, then adding to the nested list, should return all the items so that the update reflects that the property has a new value added.
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/181 …
> Fixes for nested IBackedModel properties in the InMemoryBackingStore

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Store/InMemoryBackingStoreTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1980
Changes store dictionaries to `ConcurrentDictionary` instance to alleviate race conditions from possible concurrent writes/accesses.
> Fix race conditions in backing store

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
In [Issue #81](https://github.com/microsoft/kiota-abstractions-dotnet/issues/81) @seruminar described why URIs don't contain query parameters when the models they are derived from have pascal cased property names.
Here is my short take on the problem:
- When the URL template contains query parameters with upper case first letters and the QueryParameters contains them in lowerCase (because they are added using x.Name.ToFirstCharacterLowerCase()) then the names are not matched and the resulting URI does not contain the parameters.
- When in the URI getter the parameters are actually set using uriTemplate.SetParameter then in the dictionary the casing does not match, and therefore they are silently failing to be set.
- The UriTemplate ctor contains the optional setting …
> Issue #81: Fix case insensitivity bug

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Store/InMemoryBackingStoreTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/store/InMemoryBackingStore.cs
This PR closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1994. 
It fixes a bug where multiple duplicate subscriptions would be added to collection properties when subscribing to changes in the collection. This PR updates the subscription to use the property name as unique key to avoid duplicate subscriptions being added and therefore having the side effect of each having to be invoked on a change causing the delayed execution observed in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1994. 
Tests have also been updated to capture the scenario.
> Fix for duplicate subscription creation in InMemoryBackingStore

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
Added sanitization for guid to fix issue 128
Fixes #128
> fix: issue 128 - Added sanitization for guid

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
Forgot to actually use `TryAdd` ...
> Use TryAdd when setting Content-Type

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
related https://github.com/microsoft/kiota/issues/3377
>  - adds a method to specify the content type of the binary request body

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
Closes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2193
> Fixes sanitazation of date and time values in path/query parameters

- .github/workflows/build-and-test.yml
This PR switches to windows runner for build and test GH action as net framework tests are randomly crashing on linux runners.
> Switch to windows runner for build and test GH action

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
This adds a missing `DynamicallyAccessedMembers` on Configure that means that the `DynamicallyAccessedMembers` annotation on `AddQueryParameters` is not fulfilled.
This PR does not have an associated open issue, but is related to https://github.com/microsoft/kiota/issues/4065
Example warning using Microsoft.Kiota.Abstractions 1.7.8
```
ILC : Trim analysis warning IL2091: Microsoft.Kiota.Abstractions.RequestInformation.Configure<T>(Action`1<RequestConfig
uration`1<!!0>>): 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in 'Microsoft
.Kiota.Abstractions.RequestInformation.AddQueryParameters<T>(!!0)'. The generic parameter 'T' of 'Microsoft.Kiota.Abstr
actions.RequestInformation.Configure<T>(Action`1<RequestConfiguration`1<!!0>>)' does not have …
```
> Add missing DynamicallyAccessedMembers annotation

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- Microsoft.Kiota.Abstractions.sln
- src/Microsoft.Kiota.Abstractions.csproj
Upgrade the `Std.UriTemplate` lib to 0.54 and add a unit test.
Related to observed behavior here: https://github.com/std-uritemplate/std-uritemplate/issues/114
> Upgrade the `Std.UriTemplate` lib to 0.54 and add a unit test.

- .azure-pipelines/ci-build.yml
Resolves https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2355 for Abstractions library
> Move abstractions pipelines to 1ES compliant templates

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/MultipartBodyTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/MultipartBody.cs
Fixes #212.
This adds a class to hold information about a part added to a `MultipartBody`. In addition to that, it is now possible to pass a file name to the `AddOrReplacePart` method, that will be added to the `Content-Disposition` header when serializing.
> Implement MultipartBody filename

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
Will not only include System.Diagnositics.DiagnosticSource on frameworks prior to net 6
Closes #218
> #218 tweak when System.Diagnositics.DiagnosticSource is included

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/Serialization/SerializationHelpersTests.cs
- src/serialization/KiotaJsonSerializer.Serialization.cs
- src/serialization/KiotaSerializer.Serialization.cs
> - adds async overloads for serialization

- src/Microsoft.Kiota.Abstractions.csproj
Missed the csproj version bump in https://github.com/microsoft/kiota-abstractions-dotnet/pull/233 and https://github.com/microsoft/kiota-abstractions-dotnet/pull/225
> Bump version for release.

- CHANGELOG.md
- src/Microsoft.Kiota.Abstractions.csproj
- src/serialization/KiotaSerializer.Serialization.cs
> Removes GetAwaiter() from KiotaSerializer.GetStringFromStream method

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/Time.cs
it's either escaping with backslash to opt-out of colon's "special meanings" or explicitly specifying second argument `CultureInfo.GetCultureInfo("en-US")` to prevent it from rendering other separators.
see https://github.com/dotnet/runtime/issues/90300 and https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#timeSeparator
took me three hours to figure out why the heck a test fails on one machine but not on the other..
> fix time formatting for other cultures

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/MultipartBodyTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/MultipartBody.cs
> When MultipartBody is serialized the values are generated with CRLF

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Date.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/RequestInformation.cs
- src/Time.cs
> Add support for DateOnly and TimeOnly through implicit operator conversion

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/IEnumerableExtensionsTests.cs
- src/Microsoft.Kiota.Abstractions.csproj
- src/extensions/IEnumerableExtensions.cs
part of https://github.com/microsoft/kiota/issues/4732
> Add ext. methods to replace LINQ in generated code

- CHANGELOG.md
- Microsoft.Kiota.Abstractions.Tests/EnumHelperTests.cs
- Microsoft.Kiota.Abstractions.Tests/Mocks/TestEnum.cs
- Microsoft.Kiota.Abstractions.Tests/Mocks/TestEnumWithFlags.cs
- Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- src/Helpers/EnumHelpers.cs
- src/IRequestAdapter.cs
- src/Microsoft.Kiota.Abstractions.csproj
Closes #258
Generic method is same as the current method implemented in https://github.com/microsoft/kiota-serialization-json-dotnet/blob/d0454daecb7ec2327f3e55d642fa510cf617e8b5/src/JsonParseNode.cs#L214
> Helper for parsing enums from string

- .azure-pipelines/ci-build.yml
- Directory.Build.props
Closes https://github.com/microsoft/kiota-dotnet/issues/238
Publishes new release of Kiota libraries with all versions aligned after validation of preview releases.
> Release 1.9.8

- src/abstractions/MultipartBody.cs
- src/http/httpClient/HttpClientRequestAdapter.cs
- src/http/httpClient/Middleware/ParametersNameDecodingHandler.cs
- src/serialization/form/FormParseNode.cs
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
> chore: code linting

- CHANGELOG.md
- Directory.Build.props
- Microsoft.Kiota.sln
- src/Directory.Build.props
- src/abstractions/Helpers/EnumHelpers.cs
- src/abstractions/IRequestAdapter.cs
- src/abstractions/serialization/IParseNode.cs
- src/http/httpClient/HttpClientRequestAdapter.cs
- src/serialization/form/FormParseNode.cs
- src/serialization/json/JsonParseNode.cs
- src/serialization/json/JsonSerializationWriter.cs
- src/serialization/text/TextParseNode.cs
- tests/abstractions/EnumHelperTests.cs
- tests/http/httpClient/RequestAdapterTests.cs
- tests/serialization/json/JsonParseNodeTests.cs
- tests/serialization/text/Mocks/TestEnum.cs
- tests/serialization/text/TextParseNodeTests.cs
- tests/trimming/Microsoft.Kiota.Trimming.Validation/Directory.Build.props
- tests/trimming/Microsoft.Kiota.Trimming.Validation/Microsoft.Kiota.Trimming.Validation.csproj
- tests/trimming/Microsoft.Kiota.Trimming.Validation/Program.cs
> SendPrimitiveAsync throws InvalidOperationException for enums

- Directory.Build.props
- src/Directory.Build.props
Follow up to #291 
Update script target to position of `Directory.Build.props` to ensure SignAssembly attributes are located correctly.
> Fixes release

- CHANGELOG.md
- Directory.Build.props
- src/http/httpClient/KiotaClientFactory.cs
- src/http/httpClient/Middleware/CompressionHandler.cs
- tests/http/httpClient/KiotaClientFactoryTests.cs
- tests/http/httpClient/Middleware/CompressionHandlerTests.cs
> fix: automatic decompression of response content

- CHANGELOG.md
- Directory.Build.props
- src/serialization/json/JsonSerializationWriter.cs
- tests/serialization/json/JsonSerializationWriterTests.cs
> Add support to JsonSerializationWriter.WriteNonParsableObjectValue for anonymous objects.

- CHANGELOG.md
- Directory.Build.props
- src/abstractions/store/InMemoryBackingStore.cs
- tests/abstractions/Store/InMemoryBackingStoreTests.cs
https://github.com/microsoft/kiota-dotnet/pull/326#issuecomment-2287026377
> fix: performance issue with InMemoryBackingStore

- CHANGELOG.md
- Directory.Build.props
- src/serialization/json/JsonParseNode.cs
- src/serialization/json/JsonSerializationWriter.cs
context https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2588#issuecomment-2292490939
> feat: replaces convert base64 by STJ base64 for performance

- CHANGELOG.md
- Directory.Build.props
- src/abstractions/RequestInformation.cs
- src/abstractions/serialization/IParseNodeFactory.cs
- src/abstractions/serialization/KiotaJsonSerializer.Deserialization.cs
- src/abstractions/serialization/KiotaJsonSerializer.Serialization.cs
- src/abstractions/serialization/KiotaSerializer.Deserialization.cs
- src/abstractions/serialization/KiotaSerializer.Serialization.cs
- src/abstractions/serialization/ParseNodeFactoryRegistry.cs
- src/abstractions/serialization/ParseNodeProxyFactory.cs
- src/authentication/azure/AzureIdentityAccessTokenProvider.cs
- src/authentication/azure/AzureIdentityAuthenticationProvider.cs
- src/http/httpClient/Middleware/CompressionHandler.cs
- src/serialization/json/JsonParseNodeFactory.cs
> fix: optional parameters alignments for serialization methods

- CHANGELOG.md
- Directory.Build.props
- src/abstractions/store/InMemoryBackingStore.cs
- tests/abstractions/Store/InMemoryBackingStoreTests.cs
As requested in #347 
The idea is to skip tracking the change state until the `ReturnOnlyChangedValues` property is true.
> Only track changed values when it matters

- CHANGELOG.md
- Directory.Build.props
- src/abstractions/serialization/IParsable.cs
- src/abstractions/serialization/ParsableExtensions.cs
- src/serialization/json/ParsableJsonExtensions.cs
Fixed Extension methods for make serializing easier #338
> Parsable extensions

- CHANGELOG.md
- Directory.Build.props
- src/serialization/json/JsonSerializationWriter.cs
- tests/serialization/json/JsonSerializationWriterTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2729
The pattern matching in the code does not match a collection of stucts like DateTime or DateTimeOffsets leading to the error as its handled incorrecty. 
https://github.com/microsoft/kiota-dotnet/blob/cd987c2271d760ae81d3267a1af7782378acb90a/src/serialization/json/JsonSerializationWriter.cs#L528
> fix: serialization of primitives present in additionalData

- Directory.Build.props
- src/http/httpClient/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- src/serialization/json/Microsoft.Kiota.Serialization.Json.csproj
uses nuget suppressions like in https://github.com/microsoft/OpenApi.ApiManifest/pull/119 so we're aware of any future CVE
> chore: uses nuget suppressions for CVEs

- .azure-pipelines/ci-build.yml
closes https://github.com/microsoft/kiota-dotnet/issues/477
> Update release pipeline labels for 1ES compliance

- CHANGELOG.md
- Directory.Build.props
- src/http/httpClient/KiotaClientFactory.cs
- src/http/httpClient/Middleware/BodyInspectionHandler.cs
- src/http/httpClient/Middleware/Options/BodyInspectionHandlerOption.cs
- tests/http/httpClient/Middleware/BodyInspectionHandlerTests.cs
Closes #482
Docs updates done via https://github.com/MicrosoftDocs/openapi-docs/pull/140.
> feat: add BodyInspectionHandler

- CHANGELOG.md
- src/abstractions/serialization/IParseNode.cs
- src/serialization/json/JsonParseNode.cs
> fix: nullability information

- CHANGELOG.md
- Directory.Build.props
- src/http/httpClient/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- src/http/httpClient/Middleware/BodyInspectionHandler.cs
- src/serialization/json/Microsoft.Kiota.Serialization.Json.csproj
- tests/http/httpClient/Middleware/BodyInspectionHandlerTests.cs
> Fixed response body inspection

- src/abstractions/MultipartBody.cs
- tests/abstractions/MultipartBodyTests.cs
- change MultiPartbody internal dictionary key from string to Tuple<string, string?)
- Add additional method overloads for GetPartValue<T> RemovePart
- Add EqualityComparer fro Tuple<string, string?>
- Add failing Test showcasing the imminent breaking change
- Add passing Test verifying the new intened behaviour
Fixes: #529
> MultiPartBody: Add Support for multiple Body Parts with the same name
