microsoft/kiota-dotnet

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/Serialization/ParseNodeFactoryRegistryTests.cs
Microsoft.Kiota.Abstractions.Tests/Serialization/SerializationWriterFactoryRegistryTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/serialization/ParseNodeFactoryRegistry.cs
src/serialization/SerializationWriterFactoryRegistry.cs

related https://github.com/microsoft/kiota/pull/1461

- adds support for vendor specific content types

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj
src/serialization/IParsable.cs

related https://github.com/microsoft/kiota/issues/1490
DO NOT MERGE BEFORE THE GENERATION PR GETS MERGED

- simplifies the deserializers

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/QueryParametersBaseTests.cs
src/QueryParameterAttribute.cs
src/QueryParametersBase.cs

related https://github.com/microsoft/kiota/issues/1445

- adds support for query parameter attribute

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/authentication/AnonymousAuthenticationProvider.cs
src/authentication/BaseBearerTokenAuthenticationProvider.cs
src/authentication/IAccessTokenProvider.cs
src/authentication/IAuthenticationProvider.cs

related https://github.com/microsoft/kiota/issues/1179

CAE support

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/Authentication/ApiKeyAuthenticationProviderTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/authentication/ApiKeyAuthenticationProvider.cs

related https://github.com/microsoft/kiota/issues/1902

- adds an API key authentication provider

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/RequestInformation.cs

related https://github.com/microsoft/kiota/issues/1927

- fixes a bug where request bodies that are collections of single items would not serialize properly

---

.vscode/settings.json
.vscode/tasks.json
CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
Microsoft.Kiota.Abstractions.Tests/RequestHeadersTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/RequestHeaders.cs
src/RequestInformation.cs

DO NOT MERGE BEFORE https://github.com/microsoft/kiota/pull/2045
related https://github.com/microsoft/kiota/issues/2032

- adds support for multi-valued headers

---

CHANGELOG.md
src/IRequestAdapter.cs
src/Microsoft.Kiota.Abstractions.csproj

related https://github.com/microsoft/kiota/issues/2084

 - adds the conversion method

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj
src/serialization/ISerializationWriter.cs
src/serialization/ParseNodeHelper.cs

related https://github.com/microsoft/kiota/pull/2171
@andrueastman would you mind propagating the update to serialization libraries please?

- relaxes nullability tolerance when merging objects for composed types

---

CHANGELOG.md
src/ApiException.cs
src/Microsoft.Kiota.Abstractions.csproj

related https://github.com/microsoft/kiota/issues/2216

- adds the status code to api exception

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj

Release 1.0.0

---

CHANGELOG.md
src/ApiException.cs
src/Microsoft.Kiota.Abstractions.csproj

Related to https://github.com/microsoft/kiota/issues/2524

Adds response headers to APIException

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/RequestHeadersTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/RequestHeaders.cs

This is related to the bug I submitted on msgraph-sdk-dotnet: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1951

Only allow one value on certain headers

---

src/Microsoft.Kiota.Abstractions.csproj

related https://github.com/microsoft/kiota/issues/2757

- adds missing package icon

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
src/RequestInformation.cs

issue 127 - Do not set first character of query parameter name to lower case
Fixes #127

fix: issue 127 - 

---

CHANGELOG.md
Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
src/Microsoft.Kiota.Abstractions.csproj
src/RequestInformation.cs

Fixes missing parameter values on empty strings

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj
src/serialization/ISerializationWriter.cs

Addresses https://github.com/microsoft/kiota-serialization-json-dotnet/pull/175

Fix annotations for WriteCollectionOfEnumValues

---

.github/workflows/build-and-test.yml

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

- fixes codeql permissions

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj

Updates target framework to include net6.0 and net8.0
Relates to #196

Add net6.0 and net8.0 as Target Frameworks

---

CHANGELOG.md
src/Microsoft.Kiota.Abstractions.csproj

Set license expression on package
Closes #219

#219 set license expression

---

scripts/ValidateProjectVersionUpdated.ps1

Related to https://github.com/microsoft/kiota/pull/4826

Fix version update script

---

tests/trimming/Microsoft.Kiota.Trimming.Validation/Microsoft.Kiota.Trimming.Validation.csproj

thanks to comments in https://github.com/microsoft/OpenAPI.NET/pull/1717 there are additional configuration we can apply to perform additional validation

ci: adds additional trimming testing project configuration

---

CHANGELOG.md
Directory.Build.props
src/abstractions/store/InMemoryBackingStore.cs
tests/abstractions/Store/InMemoryBackingStoreTests.cs

fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2563

fix: performance issue with the backing store

---

.azure-pipelines/ci-build.yml

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

ci: upgrades esrp sign tasks

---

.azure-pipelines/ci-build.yml

Signed-off-by: Vincent Biret <vibiret@microsoft.com>

ci: upgrades outdated task

---

CHANGELOG.md
Directory.Build.props
src/http/httpClient/HttpClientRequestAdapter.cs
src/http/httpClient/Middleware/RedirectHandler.cs
src/http/httpClient/Middleware/RetryHandler.cs

Updates the http span attributes to match with the updated OTEL specification.
closes #344

fix(spans): adhere attribute name to otel semver

---

CHANGELOG.md
Directory.Build.props
src/http/httpClient/Microsoft.Kiota.Http.HttpClientLibrary.csproj

fix: diagnostic source version

---

src/abstractions/Microsoft.Kiota.Abstractions.csproj
src/authentication/azure/Microsoft.Kiota.Authentication.Azure.csproj
src/http/httpClient/Microsoft.Kiota.Http.HttpClientLibrary.csproj
src/serialization/json/Microsoft.Kiota.Serialization.Json.csproj

removes upper bounds in https://github.com/microsoft/OpenApi.ApiManifest/pull/117

fix: removes upper bounds to avoid locking upgrades

---

.github/policies/kiota-dotnet-branch-protection.yml

ci: adds branch policy definition

---

src/http/httpClient/KiotaClientFactory.cs

I went with the struct wrapper as it's a bit nicer than implementing a custom enumerator IMO.
Closes #518

feat: Add trim-safe handler lookup
